# Generated by Django 5.1 on 2024-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="post/%Y/%m/%d"),
        ),
    ]
