# Generated by Django 5.1 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="proverbs",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
