# Generated by Django 5.1 on 2024-08-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_proverbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="proverbs_author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
