# Generated by Django 5.1 on 2024-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_proverbs_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
